# Server配置
server:
  port: 8095

spring:
  application:
    name: service-feign

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 日志配置
logging:
  file: log/service-feign.log
  level:
    com.ktjr: debug
    org.springfromework.web: info