# Server配置
server:
  port: 8091

spring:
  application:
    name: service-ribbon

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 日志配置
logging:
  file: log/service-ribbon.log
  level:
    com.ktjr: debug
    org.springfromework.web: info
