# Server配置
server:
  port: 8096

spring:
  application:
    name: service-feign

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 日志配置
logging:
  file: log/service-feign-hystrix.log
  level:
    com.ktjr: debug
    org.springfromework.web: info

# 启用熔断功能
feign:
  hystrix:
    enabled: true